name: CI/CD pipeline

on:
  push:
    branches: ["main", "development"]
  pull_request:
    branches: ["main", "development"]

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      # Run Backend Tests
      - name: Install and Test (Backend)
        run: |
          cd backend
          npm install
          npm test

      # Run Frontend Tests
      - name: Install and Test (Frontend)
        run: |
          cd frontend
          npm install
          npm test

  docker-publish:
    # Only run this job if the 'run-tests' job succeeds
    needs: run-tests
    runs-on: ubuntu-latest

    # Optional: only publish if we're on main (you can remove 'if:' if you want to publish from dev too)
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      # 1) Log in to Docker Hub (or your registry of choice)
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          registry: docker.io
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      # 2) Build and push the image
      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/taskmanagment:latest
